"""init paper model

Revision ID: b98da81ccff5
Revises: 
Create Date: 2026-07-23 12:17:41.112320
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b98da81ccff5'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('arxiv_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('authors', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('categories', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('published_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pdf_url', sa.Text(), nullable=False),
    sa.Column('doi', sa.Text(), nullable=True),
    sa.Column('pdf_object_key', sa.Text(), nullable=True),
    sa.Column('parsed_json_object_key', sa.Text(), nullable=True),
    sa.Column('parser_name', sa.String(length=64), nullable=True),
    sa.Column('parser_error', sa.Text(), nullable=True),
    sa.Column('ingestion_status', sa.String(length=32), nullable=False),
    sa.Column('parser_status', sa.String(length=32), nullable=False),
    sa.Column('indexing_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_papers_arxiv_id'), 'papers', ['arxiv_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_papers_arxiv_id'), table_name='papers')
    op.drop_table('papers')
    # ### end Alembic commands ###